name: time_trace

server:
  listen: localhost
  port: "7070"

log:
  path: log.ttrace
  targets:
  - file
  - console
  level: debug
  colorful: true
  compress: true
  max_age: 1
  max_backups: 10
  max_log_size: 10

users:
- name: root
  password: super_secret_password
  cmds:
  - '*'

# Also you can use this for multiple users and limited commands
# users:
#   - name: root
#     password: super_secret_password
#     cmd:
#       - '*' # all commands.
#   - name: developer
#     password: secret_password
#     cmd:
#       - 'GET'
#       - 'PUSH'
#       - 'DEL'